name: deploy

on:
    # 원래 여기에 push 이벤트가 들어갔어야 하는데 `workflow_dispatch`라는 키워드가 들어갔죠?
    # 즉, "workflow를 수동으로 trigger시킬게"라는 의미입니다.
    workflow_dispatch:
        # 값도 받을 수 있습니다. region, env 말고 원하시는 값들을 받을 수도 있겠죠?
        inputs:
            tags:
                description: 'Test tags'

jobs:
    deploy:
        name: deploy project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Build
              uses: appleboy/ssh-action@v1.0.3
              with:
                  key: ${{secrets.SSH_KEY}}
                  host: ${{secrets.AWS_PUBLIC_DNS}}
                  username: ${{secrets.AWS_USERNAME}}
                  script: |
                      whoami
                      cd /home/ubuntu/app/dev-morph-blog
                      git pull origin main
                      touch .env
                      echo "NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}}" > ./.env
                      echo "API_BASE_URL=${{secrets.API_BASE_URL}}" >> ./.env
                      echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> ./.env
                      echo "AWS_S3_ACCESS_KEY=${{secrets.AWS_S3_ACCESS_KEY}}" >> ./.env
                      echo "AWS_S3_SECRET_KEY=${{secrets.AWS_S3_SECRET_KEY}}" >> ./.env
                      echo "AWS_S3_BASE_URL=${{secrets.AWS_S3_BASE_URL}}" >> ./.env
                      echo "NEXT_PUBLIC_AWS_S3_BASE_URL=${{secrets.NEXT_PUBLIC_AWS_S3_BASE_URL}}" >> ./.env
                      echo "ELASTIC_PASSWORD=${{secrets.ELASTIC_PASSWORD}}" >> ./.env
                      echo "KIBANA_PASSWORD=${{secrets.KIBANA_PASSWORD}}" >> ./.env
                      echo "ES_PORT=${{secrets.ES_PORT}}" >> ./.env
                      echo "KIBANA_PORT=${{secrets.KIBANA_PORT}}" >> ./.env
                      echo "ES_MEM_LIMIT=${{secrets.ES_MEM_LIMIT}}" >> ./.env
                      echo "KB_MEM_LIMIT=${{secrets.KB_MEM_LIMIT}}" >> ./.env
                      echo "LS_MEM_LIMIT=${{secrets.LS_MEM_LIMIT}}" >> ./.env
                      echo "ENCRYPTION_KEY=${{secrets.ENCRYPTION_KEY}}" >> ./.env
                      echo "Success Git Pull"
                      sudo npm ci
                      sudo npm run build
                      sudo pm2 reload blog
